### ISSUE TITLE
[FR]: Import data from csv

### ISSUE THREAD

**Issue by arminta7** [SkepticMystic/import-into-obsidian#1]
I'd like to have an import feature so I can pull in all of my all tracking data from the csv it's in. 

Each row is a date, so all of the fields and their values should be appended to the appropriate DNP as inline metadata. Numerical fields as `Field:: 3.5`. Binary fields like those under Mood or Foods should be shown as `Foods:: [[Banana]], [[Salmon]], [[Smoothie]]` and `Mood:: [[Angry]], [[Anxious]]`. Keep in mind an item like [[Banana]] would be a column in the csv with a value of 1 or 0.

**Comment by SkepticMystic** [comment]
@person-al, I've got a repo up and running for this separate plugin. I've made quite alot of progress, but there is still lots to do :)

**Comment by person-al** [comment]
@SkepticMystic This looks great so far! What's the highest priority remaining work? Feel free to make a bunch of issues to track remaining work and assign whatever you'd like to me. This is great progress.

**Comment by SkepticMystic** [comment]
@person-al thanks! I will do. There was one remaining FR/bug, but I think that's resolved now. Waiting to hear back from @arminta7 if the new features work :)

**Comment by person-al** [comment]
@SkepticMystic I think we can close this issue for now? @arminta7 please open new issues for any remaining work here: thanks!
